### ISSUE TITLE
Server crash at RoundEnd

### ISSUE THREAD

**Issue by Cruze03** [Sples1/ENT_Hosties#12]
I host a multimod server with Jailbreak mod in it. All mods are working perfectly, only jailbreak causes crash and I'm like 99% sure (with some hit and trials) that it's caused by this hosties plugin. Pretty random crash (usually happens randomly after 1st round) but only happens when round ends though. No error logs and crash reports doesn't tell much about it. https://crash.limetech.org/tncmzpcagrmx
Other than that crash, this plugin is lit ❤️

**Comment by Sples1** [comment]
**Dear Cruze03**

One of the members in my Discord community had the same problem, but he found it out it's caused by his store plugin got outdated. We test all versions with the Discord community before upload. Also there is no other reports about that (none in Discord and none in anywhere else). 

If you have any issues with hosties it's better to report it on Discord, because I can help you in real time with it.

**Comment by Cruze03** [comment]
Are you sure it's caused by Zephyrus store plugin? O.o

**Comment by Sples1** [comment]
For anyone who ready this:

This bug was caused by armsfix, nőt hosties.
